//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.06 at 06:42:35 PM UZT 
//


package uz.asbt.digid.mipservice.types.stc.getTaxInfobyId;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="err_code" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="err_text" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="root"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="list"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="BRANCH_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="TITLE_UZ" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="TITTLE_RU" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "errCode",
    "errText",
    "root"
})
@XmlRootElement(name = "getTaxInfobyIdRes")
public class GetTaxInfobyIdRes {

    @XmlElement(name = "err_code", required = true)
    protected String errCode;
    @XmlElement(name = "err_text", required = true)
    protected String errText;
    @XmlElement(required = true)
    protected GetTaxInfobyIdRes.Root root;

    /**
     * Gets the value of the errCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getErrCode() {
        return errCode;
    }

    /**
     * Sets the value of the errCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setErrCode(String value) {
        this.errCode = value;
    }

    /**
     * Gets the value of the errText property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getErrText() {
        return errText;
    }

    /**
     * Sets the value of the errText property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setErrText(String value) {
        this.errText = value;
    }

    /**
     * Gets the value of the root property.
     *
     * @return
     *     possible object is
     *     {@link GetTaxInfobyIdRes.Root }
     *
     */
    public GetTaxInfobyIdRes.Root getRoot() {
        return root;
    }

    /**
     * Sets the value of the root property.
     *
     * @param value
     *     allowed object is
     *     {@link GetTaxInfobyIdRes.Root }
     *
     */
    public void setRoot(GetTaxInfobyIdRes.Root value) {
        this.root = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="list"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="BRANCH_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="TITLE_UZ" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="TITTLE_RU" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "list"
    })
    public static class Root {

        @XmlElement(required = true)
        protected GetTaxInfobyIdRes.Root.List list;

        /**
         * Gets the value of the list property.
         *
         * @return
         *     possible object is
         *     {@link GetTaxInfobyIdRes.Root.List }
         *
         */
        public GetTaxInfobyIdRes.Root.List getList() {
            return list;
        }

        /**
         * Sets the value of the list property.
         *
         * @param value
         *     allowed object is
         *     {@link GetTaxInfobyIdRes.Root.List }
         *
         */
        public void setList(GetTaxInfobyIdRes.Root.List value) {
            this.list = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="BRANCH_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="TITLE_UZ" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="TITTLE_RU" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "branchcode",
            "titleuz",
            "tittleru"
        })
        public static class List {

            @XmlElement(name = "BRANCH_CODE", required = true)
            protected String branchcode;
            @XmlElement(name = "TITLE_UZ", required = true)
            protected String titleuz;
            @XmlElement(name = "TITTLE_RU", required = true)
            protected String tittleru;

            /**
             * Gets the value of the branchcode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBRANCHCODE() {
                return branchcode;
            }

            /**
             * Sets the value of the branchcode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBRANCHCODE(String value) {
                this.branchcode = value;
            }

            /**
             * Gets the value of the titleuz property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTITLEUZ() {
                return titleuz;
            }

            /**
             * Sets the value of the titleuz property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTITLEUZ(String value) {
                this.titleuz = value;
            }

            /**
             * Gets the value of the tittleru property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTITTLERU() {
                return tittleru;
            }

            /**
             * Sets the value of the tittleru property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTITTLERU(String value) {
                this.tittleru = value;
            }

            @Override
            public String toString() {
                return "List{" +
                        "branchcode='" + branchcode + '\'' +
                        ", titleuz='" + titleuz + '\'' +
                        ", tittleru='" + tittleru + '\'' +
                        '}';
            }
        }

        @Override
        public String toString() {
            return "Root{" +
                    "list=" + list +
                    '}';
        }
    }

    @Override
    public String toString() {
        return "GetTaxInfobyIdRes{" +
                "errCode='" + errCode + '\'' +
                ", errText='" + errText + '\'' +
                ", root=" + root +
                '}';
    }
}
