//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.11 at 03:41:20 PM UZT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:megaware:http:operation:098FD8BE-E57F-4F28-8D02-298B2324F2A2")
package uz.asbt.digid.mipservice.types.stc.getTaxInfobyId;
