//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.06 at 06:42:35 PM UZT 
//


package uz.asbt.digid.mipservice.types.moi.getPlacesByDistrictId;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="return" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="SP_ACTIVE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="SP_DATEENTER" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *                   &lt;element name="SP_DISTRICT" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *                   &lt;element name="SP_ID" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *                   &lt;element name="SP_IDFIRST" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *                   &lt;element name="SP_IDOLD" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *                   &lt;element name="SP_NAME00" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="SP_NAME01" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="SP_NAME02" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="SP_NAME03" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="SP_NAME04" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="SP_NAME05" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="SP_REGION" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *                   &lt;element name="SP_SCN" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "_return"
})
@XmlRootElement(name = "getPlacesByDistrictIdResponse")
public class GetPlacesByDistrictIdResponse {

    @XmlElement(name = "return")
    protected List<Return> _return;

    /**
     * Gets the value of the return property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the return property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReturn().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GetPlacesByDistrictIdResponse.Return }
     *
     *
     */
    public List<Return> getReturn() {
        if (_return == null) {
            _return = new ArrayList<Return>();
        }
        return this._return;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="SP_ACTIVE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="SP_DATEENTER" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
     *         &lt;element name="SP_DISTRICT" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
     *         &lt;element name="SP_ID" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
     *         &lt;element name="SP_IDFIRST" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
     *         &lt;element name="SP_IDOLD" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
     *         &lt;element name="SP_NAME00" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="SP_NAME01" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="SP_NAME02" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="SP_NAME03" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="SP_NAME04" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="SP_NAME05" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="SP_REGION" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
     *         &lt;element name="SP_SCN" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "spactive",
        "spdateenter",
        "spdistrict",
        "spid",
        "spidfirst",
        "spidold",
        "spname00",
        "spname01",
        "spname02",
        "spname03",
        "spname04",
        "spname05",
        "spregion",
        "spscn"
    })
    public static class Return {

        @XmlElement(name = "SP_ACTIVE")
        protected String spactive;
        @XmlElement(name = "SP_DATEENTER")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar spdateenter;
        @XmlElement(name = "SP_DISTRICT")
        protected Long spdistrict;
        @XmlElement(name = "SP_ID")
        protected Long spid;
        @XmlElement(name = "SP_IDFIRST")
        protected Long spidfirst;
        @XmlElement(name = "SP_IDOLD")
        protected Long spidold;
        @XmlElement(name = "SP_NAME00")
        protected String spname00;
        @XmlElement(name = "SP_NAME01")
        protected String spname01;
        @XmlElement(name = "SP_NAME02")
        protected String spname02;
        @XmlElement(name = "SP_NAME03")
        protected String spname03;
        @XmlElement(name = "SP_NAME04")
        protected String spname04;
        @XmlElement(name = "SP_NAME05")
        protected String spname05;
        @XmlElement(name = "SP_REGION")
        protected Long spregion;
        @XmlElement(name = "SP_SCN")
        protected Long spscn;

        /**
         * Gets the value of the spactive property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSPACTIVE() {
            return spactive;
        }

        /**
         * Sets the value of the spactive property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSPACTIVE(String value) {
            this.spactive = value;
        }

        /**
         * Gets the value of the spdateenter property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getSPDATEENTER() {
            return spdateenter;
        }

        /**
         * Sets the value of the spdateenter property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setSPDATEENTER(XMLGregorianCalendar value) {
            this.spdateenter = value;
        }

        /**
         * Gets the value of the spdistrict property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getSPDISTRICT() {
            return spdistrict;
        }

        /**
         * Sets the value of the spdistrict property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setSPDISTRICT(Long value) {
            this.spdistrict = value;
        }

        /**
         * Gets the value of the spid property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getSPID() {
            return spid;
        }

        /**
         * Sets the value of the spid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setSPID(Long value) {
            this.spid = value;
        }

        /**
         * Gets the value of the spidfirst property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getSPIDFIRST() {
            return spidfirst;
        }

        /**
         * Sets the value of the spidfirst property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setSPIDFIRST(Long value) {
            this.spidfirst = value;
        }

        /**
         * Gets the value of the spidold property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getSPIDOLD() {
            return spidold;
        }

        /**
         * Sets the value of the spidold property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setSPIDOLD(Long value) {
            this.spidold = value;
        }

        /**
         * Gets the value of the spname00 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSPNAME00() {
            return spname00;
        }

        /**
         * Sets the value of the spname00 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSPNAME00(String value) {
            this.spname00 = value;
        }

        /**
         * Gets the value of the spname01 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSPNAME01() {
            return spname01;
        }

        /**
         * Sets the value of the spname01 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSPNAME01(String value) {
            this.spname01 = value;
        }

        /**
         * Gets the value of the spname02 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSPNAME02() {
            return spname02;
        }

        /**
         * Sets the value of the spname02 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSPNAME02(String value) {
            this.spname02 = value;
        }

        /**
         * Gets the value of the spname03 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSPNAME03() {
            return spname03;
        }

        /**
         * Sets the value of the spname03 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSPNAME03(String value) {
            this.spname03 = value;
        }

        /**
         * Gets the value of the spname04 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSPNAME04() {
            return spname04;
        }

        /**
         * Sets the value of the spname04 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSPNAME04(String value) {
            this.spname04 = value;
        }

        /**
         * Gets the value of the spname05 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSPNAME05() {
            return spname05;
        }

        /**
         * Sets the value of the spname05 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSPNAME05(String value) {
            this.spname05 = value;
        }

        /**
         * Gets the value of the spregion property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getSPREGION() {
            return spregion;
        }

        /**
         * Sets the value of the spregion property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setSPREGION(Long value) {
            this.spregion = value;
        }

        /**
         * Gets the value of the spscn property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getSPSCN() {
            return spscn;
        }

        /**
         * Sets the value of the spscn property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setSPSCN(Long value) {
            this.spscn = value;
        }

        @Override
        public String toString() {
            return "Return{" +
                    "spactive='" + spactive + '\'' +
                    ", spdateenter=" + spdateenter +
                    ", spdistrict=" + spdistrict +
                    ", spid=" + spid +
                    ", spidfirst=" + spidfirst +
                    ", spidold=" + spidold +
                    ", spname00='" + spname00 + '\'' +
                    ", spname01='" + spname01 + '\'' +
                    ", spname02='" + spname02 + '\'' +
                    ", spname03='" + spname03 + '\'' +
                    ", spname04='" + spname04 + '\'' +
                    ", spname05='" + spname05 + '\'' +
                    ", spregion=" + spregion +
                    ", spscn=" + spscn +
                    '}';
        }
    }

    @Override
    public String toString() {
        return "GetPlacesByDistrictIdResponse{" +
                "_return=" + _return +
                '}';
    }
}
