//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.11 at 03:41:20 PM UZT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:megaware:http:operation:F3FC560C-E860-4DDA-9A6D-8E42538E07BE")
package uz.asbt.digid.mipservice.types.stc.getTaxInfobyTin;
